const projectData = [
  { key: "1914", title: "1914" },
  { key: "1914GlorysEnd", title: "1914 Glorys End" },
  { key: "1stAlamein", title: "1st Alamein" },
  { key: "AcrossSuez", title: "Across Suez" },
  { key: "AfrikaKorps", title: "Afrika Korps" },
  { key: "Alamein", title: "Alamein" },
  { key: "Antietam", title: "Antietam" },
  { key: "ArabIsraelWars", title: "Arab Israel Wars" },
  { key: "Austerlitz", title: "Austerlitz" },
  { key: "Austerlitz1805", title: "Austerlitz 1805" },
  { key: "AusterlitzSPI", title: "Austerlitz SPI" },
  { key: "BAOR", title: "BAOR" },
  { key: "BattleForAllenCreek", title: "Battle For Allen Creek" },
  { key: "BattleForMoscow", title: "Battle For Moscow" },
  { key: "BattleForMoscow3Ci", title: "Battle For Moscow 3Ci" },
  { key: "BattleOfMoscow", title: "Battle Of Moscow" },
  { key: "BattleOfShiloh", title: "Battle Of Shiloh" },
  { key: "BattleOfTheBulge", title: "Battle Of the Bulge" },
  { key: "Blitzkrieg", title: "Blitzkrieg" },
  { key: "BloodyApril", title: "Bloody April" },
  { key: "Borodino", title: "Borodino" },
  { key: "BurnishedRowsOfSteel", title: "Burnished Rows of Steel" },
  { key: "CemeteryHill", title: "Cemetery Hill" },
  { key: "Chancellorsville1", title: "Chancellorsville 1" },
  { key: "Chancellorsville2", title: "Chancellorsville 2" },
  { key: "Chancellorsville3", title: "Chancellorsville 3" },
  { key: "Chickamauga", title: "Chickamauga" },
  { key: "CromwellsVictory", title: "Cromwells Victory" },
  { key: "DeathStruggle", title: "Death Struggle" },
  { key: "D-Day", title: "D-Day" },
  { key: "DesertFox", title: "Desert Fox" },
  { key: "DriveOnKursk", title: "Drive on Kursk" },
  { key: "DriveOnMetz", title: "Drive on Metz" },
  { key: "EagleAndBear", title: "Eagle and Bear" },
  { key: "EuropeanRussia", title: "European Russia" },
  { key: "Eylau", title: "Eylau" },
  { key: "FallenEagles", title: "Fallen Eagles" },
  { key: "FirstBlood", title: "" },
  { key: "FortressStalingrad", title: "Fortress Stalingrad" },
  { key: "France1870", title: "France 1870" },
  { key: "France1914", title: "France 1914" },
  { key: "France1940", title: "France 1940" },
];

export default projectData;
